### ISSUE TITLE
regression 을 어떻게 번역해야 할까요?

### ISSUE THREAD

**Issue by jihuun** [jihuun/Linux-Documentation-KOR-Translation#94]
development-process 전체 문서에 대충세어보니 22번이나 나오는데 퇴화라고 번역하자니 뭔가 이상합니다.

**Comment by jungwoos** [comment]
역행? 그냥 regression 이라고 써야하나. 딱히 대안이 생각이 안난다.

**Comment by jihuun** [comment]
적절한 번역어를 찾을때까지 그냥 regression을 사용합시다. 일부 몇몇은 문맥에 따라 문제 및 성능감소정도로 번역해놓았어요
