### ISSUE TITLE
merge 를 어떻게번역?

### ISSUE THREAD

**Issue by jihuun** [jihuun/Linux-Documentation-KOR-Translation#95]
merge, 반영? 적용? 머지? 
저는 보통 반영으로 번역해 놓았는데 통일이 되어야 할 것같습니다.

**Comment by jungwoos** [comment]
김민찬씨도 HOWTO 번역할때 반영과 머지를 다 사용했네요.
김민찬씨 방법대로 보통 반영을 쓰고 머지 윈도우 같이 혼합어? 인 경우 머지를 쓰는게 좋을것 같습니다.

**Comment by jihuun** [comment]
넵 반영 머지 병합 혼용해서 사용하는게 좋을것 같습니다. 근데 제생각에는 영어발음 한국어로옮기는것보다 반영과 병합정도를 혼용해서 사용하는게 좋을것같아요
